name: linting_and_testing

on: workflow_dispatch
  # push:
  #   branches: [ master ]

  # Allows to run this workflow manually from the Actions tab
  

jobs:
  # Name of the Job
  lint_and_test:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - run: echo "Repository -> ${{ github.repository }}"
      - run: echo "Branch -> ${{ github.ref }}"
      - run: echo "Trigger event -> ${{ github.event_name }}"
      - run: echo "Runner OS -> ${{ runner.os }}"


      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: provision-with-micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: .github/env.yaml
          extra-specs: |
            pytest
            flake8
      
      - name: List installed package versions
        shell: bash -l {0}  # necessary for conda env to be active
        run: micromamba list

      - name: Lint with flake8
        shell: bash -l {0}  # necessary for conda env to be active
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=999 --statistics
      

      - name: Restore .bash_profile
        run: cp ~/.bash_profile_orig ~/.bash_profile


