name: linting_and_testing

on: workflow_dispatch
  # push:
  #   branches: [ master ]

  # Allows to run this workflow manually from the Actions tab
  

jobs:
  # Name of the Job
  lint_and_test:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - run: echo "Repository: ${{ github.repository }}"
      - run: echo "Branch: ${{ github.ref }}"
      - run: echo "Trigger event: ${{ github.event_name }}"
      - run: echo "Runner OS: ${{ runner.os }}"


      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: provision-with-micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: .github/env.yaml
          extra-specs: |
            pytest
      
      - name: List installed package versions
        shell: bash -l {0}  # necessary for conda env to be active
        run: micromamba list

      - name: Restore .bash_profile
        run: cp ~/.bash_profile_orig ~/.bash_profile


